### PR TITLE
Include ProseMirror bundle in repository

### LINKED ISSUE #141: Dokuwiki Prosemirror - Fails with Uncaught TypeError: window.Prosemirror is undefined
I have a new install of dokuwiki that seems to be working great, but I cannot get the prosemirror plugin to work correctly. When I click on "Toggle WYSIWYG editor" it does not load and says "There was an error in the WYSIWYG editor". 

**Edge Chromium developer tools shows this when the issue happens:**

Uncaught TypeError: Cannot read property 'enableProsemirror' of undefined
	at showProsemirror (js.php?t=dokuwiki&tseed=efed69add6c51c7ac07c7df3cbebdee9:1)
	at handleEditSession (js.php?t=dokuwiki&tseed=efed69add6c51c7ac07c7df3cbebdee9:1)
	at HTMLDocument.<anonymous> (js.php?t=dokuwiki&tseed=efed69add6c51c7ac07c7df3cbebdee9:1)
	at e (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
	at t (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
showProsemirror @ js.php?t=dokuwiki&tseed=efed69add6c51c7ac07c7df3cbebdee9:1
2js.php?t=dokuwiki&tseed=efed69add6c51c7ac07c7df3cbebdee9:1 Uncaught TypeError: Cannot read property 'destroyProsemirror' of undefined
	at showDefaultEditor (js.php?t=dokuwiki&tseed=efed69add6c51c7ac07c7df3cbebdee9:1)
	at Object.handleSwitchEditorResponse (js.php?t=dokuwiki&tseed=efed69add6c51c7ac07c7df3cbebdee9:1)
	at c (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
	at Object.fireWith [as resolveWith] (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
	at l (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
	at XMLHttpRequest.<anonymous> (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)

**Firefox developer tools shows this:**

Uncaught TypeError: window.Prosemirror is undefined

---------------------------------------------------------------------
Dokuwiki 2020-07-29 "Hogfather"
Prosemirror 2021-05-06
PHP 7.3.19
IIS - Windows 2019

### PR DESCRIPTION
**Pull request by PowerKiKi**
Because DokuWiki will download this plugin straight from GitHub, this
repository must contains all files required to run the plugin successfully.

Without this, ProseMirror would be missing and the editor would never show
up in DokuWikim instead showing the error:

```
There was an error in the WYSIWYG editor
```

And logging in the console:

```
Uncaught TypeError: window.Prosemirror is undefined
```

Fixes #141

### CODE REVIEW

**Comment by splitbrain** [comment]
The ready to install plugin should be in branch `release` and be auto build on master commits.

**Comment by PowerKiKi** [comment]
That makes a lot of sense for this repository, but unfortunately DokuWiki download from the `master` branch as can be seen in the below screenshot:

extension-manager

Is there a way to tell DokuWiki to download from another branch ?

**Comment by splitbrain** [comment]
You're right. This was wrongly setup. @annda looks like you changed it: https://www.dokuwiki.org/plugin:prosemirror?do=diff&rev2%5B0%5D=1621968867&rev2%5B1%5D=1621969120&difftype=sidebyside

**Comment by Klap-in** [comment]
@splitbrain the ‘release’ branch is last updated in October 2020, could be that this triggers @annda to change the download url?

**Comment by splitbrain** [comment]
@Klap-in yes. tests were failing because the wrap plugin (which is a dependency for testing) is not compatible with the newer test suite in master. I updated the repo to only test against stable for now. I also moved the build process from travis to githaub actions.

**Comment by tumd** [comment]
The tagged archives seem to still have this issue.
For example the latest tagged archive; https://github.com/cosmocode/dokuwiki-plugin-prosemirror/archive/refs/tags/2023-02-15.tar.gz

**Pull request closed without merging**
